### ISSUE TITLE
Hadi bismillah. fastapi'nin dockerfile'ı eksik

### ISSUE THREAD

**Issue by berkmonder** [siyahmasa/apple-stocks-prediction#1]
`docker compose up -d`

Bu hatayı veriyor;

> failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory

fastapi için dockerfile'ı da uçurmuşsun için olmalı. Servisi ayağa kaldıramadığım için deneyemedim ama postgres tarafı çalışması lazım. Rabbit kısmından emin değilim. Emin sensin xd

**Comment by carbasemin** [comment]
kardesim even we're elhamdulillah musluman, let's write in English ;)

**Comment by carbasemin** [comment]
d1abdd042d7410b590156720b3a83b38ccfcfccb
